var myFullName = "sangita Survase";
console.log("Name:",myFullName);
var myFullName = "sangita Dadasaheb Survase";
console.log("Name:",myFullName);
var myLove = "I love only js";
 console.log("my love is:",myLove);
 var firstName="sangita";
 var lastName="survase";
 var age ='23';
 var address="solapur";
 var pincode="413221";
 var gender="female";
 var isMarried= 'No';
 console.log("first name:",firstName);
 console.log("last name:",lastName);
 console.log("my age:",age);
 console.log("address:",address);
 console.log("pincode:",pincode);
 console.log("gender:",gender);
 console.log("status:",isMarried);