var myFullName = "sangita Survase";
console.log("Name:",myFullName);
var myFullName = "sangita Dadasaheb Survase";
console.log("Name:",myFullName);
var myLove = "I love only js";
 console.log("my love is:",myLove);
 var firstName="sangita";
 var lastName="survase";
 var age ='23';
 var address="solapur";
 var pincode="413221";
 var gender="female";
 var isMarried= 'no';
 console.log("first name is",firstName);
 console.log("last name is",lastName);
 console.log("my age is",age);
 console.log("address is",address);
 console.log("pincode is",pincode);
 console.log("gender:",gender);
 console.log("status:",isMarried);